### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by joeybaker**
and, hopefully re-enable watch test on linux.

### CODE REVIEW

**Comment by joeybaker** [comment]
Oh man did I have to hack the tests to get this to work. Envify doesn't play nicely on linux (anymore?).

**Comment by joeybaker** [comment]
@bclinkinbeard @Techwraith or @ben-ng can I get a code review?

**Comment by bclinkinbeard** [comment]
Looks good but after this I think we should avoid these dep upgrade efforts unless there is a compelling reason to do it. Looks like we're getting a better version of watchify here but starting to feel like churn. Thoughts?

**Comment by joeybaker** [comment]
I guess I'm just trying to be pre-emptive here. On my remapify repo, the largest source of new issues is incompatibility with new browserify releases. I'd just like to stay ahead of that problem.

**Pull request merged**
