### PR TITLE
upgrade to browserify 13.0.1

### PR DESCRIPTION
**Pull request by spacepluk**
I had some problems with browserify not applying the global transforms in the correct order, upgrading browserify fixed the issue.

### CODE REVIEW

**Comment by joeybaker** [comment]
@spacepluk thanks! I made you a collaborator here and on npm. Feel free to merge and publish.

**Comment by spacepluk** [comment]
@joeybaker Thanks! :) I'll look into it tomorrow

**Comment by spacepluk** [comment]
Hey @joeybaker, life got in the way and this took a little longer than expected, hehe.  I'm trying to merge the PR now but I think I don't have write access here.

**Comment by joeybaker** [comment]
Weird! Invitation resent.

**Comment by spacepluk** [comment]
Got it! thanks! :)

**Comment by spacepluk** [comment]
Merged and published. Do you want me to update the atomify package as well?

**Comment by joeybaker** [comment]
Sure! Thanks

**Pull request merged**
